<option value="Maputo">Maputo</option>
<option value="Gaza">Gaza</option>
<option value="Inhambane">Inhambane</option>
<option value="Sofala">Sofala</option>
<option value="Manica">Manica</option>
<option value="Tete">Tete</option>
<option value="Zambezia">Zambezia</option>
<option value="Nampula">Nampula</option>
<option value="Niassa">Niassa</option>
<option value="Cabo Delgado">Cabo Delgado</option>